version: "3"
name: desafio-03-server

services:
  api-solid-faf:
    image: bitnami/postgresql:13.16.0
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid